import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { FaFacebookSquare, FaGraduationCap, FaHeart, FaInstagramSquare, FaTwitterSquare, FaYoutubeSquare } from 'react-icons/fa';

export default function Home() {

  return (
    <>
      <Head>
        <title>Brand Bikega</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <nav className={styles.nav}>
          <div className={styles.logo}>
            <Image src="/logo.png" alt="Logo" width={40} height={40} />
          </div>
          <div className={styles.navLinks}>
            <a className={styles.navLinksItem} href="#brand">Brand</a>
            <Link className={styles.navLinksItem} href="/creaters">Creaters</Link>
            <a className={styles.navLinksItem} href="#about">About</a>
            <a className={styles.navLinksItem} href="#contact">Contact</a>
          </div>
        </nav>
        <section className={styles.hero}>
          <div className={styles.heroText}>
            <h1>Brand Bikega</h1>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam
              quod, voluptatum, quia, voluptas quas voluptates quibusdam
              voluptatibus quae quidem quos nemo. Quisquam, quae. Quisquam
              voluptates quibusdam voluptatibus quae quidem quos nemo.
            </p>
            <button><a href="#about">Learn More</a></button>
          </div>
          <div className={styles.heroImage}>
            <Image src="/hero.svg" alt="Hero" width={500} height={500} />
          </div>
          <div className={styles.waves}>
            <Image src="/wavesOpacity.svg" alt="Waves" width={1920} height={200} className={styles.wavesOpacity} />
          </div>
        </section>
        <section className={styles.about} id="about">
          <div className={styles.aboutImage}>
            <Image src="/about.jpg" alt="About" width={500} height={500} />
          </div>
          <div className={styles.aboutText}>
            <h1>About Us</h1>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam
              quod, voluptatum, quia, voluptas quas voluptates quibusdam
              voluptatibus quae quidem quos nemo. Quisquam, quae. Quisquam
              voluptates quibusdam voluptatibus quae quidem quos nemo.
            </p>
            <button>Learn More</button>
          </div>
        </section>
        <section className={styles.brand}>
          <div className={styles.brandInner}>
            <div className={styles.brandHeader}>
              <h1 className={styles.brandTitle}>
                We're ready to share our advice and experience</h1>
              <p className={styles.brandHeaderDesc}>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem
                ipsum
                dolor sit amet consectetur adipisicing elit.</p>
            </div>
            <div className={styles.brandBox}>
              <div
                className={styles.brandBoxItem}>
                <div className={styles.brandBoxItemContent}>
                  <FaGraduationCap className={styles.brandBoxItemIcon} />
                  <a href="https://www.youtube.com/watch?v=Q7o0X1Z0Z9s" target="_blank">
                    <h2 className={styles.brandBoxItemTitle}>Education</h2>
                  </a>
                  <p className={styles.brandBoxItemDesc}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                </div>
              </div>
              <div
                className={styles.brandBoxItem}>
                <div className={styles.brandBoxItemContent}>
                  <FaGraduationCap className={styles.brandBoxItemIcon} />
                  <a href="https://www.youtube.com/watch?v=Q7o0X1Z0Z9s" target="_blank">
                    <h2 className={styles.brandBoxItemTitle}>Education</h2>
                  </a>
                  <p className={styles.brandBoxItemDesc}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                </div>
              </div>
              <div
                className={styles.brandBoxItem}>
                <div className={styles.brandBoxItemContent}>
                  <FaGraduationCap className={styles.brandBoxItemIcon} />
                  <a href="https://www.youtube.com/watch?v=Q7o0X1Z0Z9s" target="_blank">
                    <h2 className={styles.brandBoxItemTitle}>Technology</h2>
                  </a>
                  <p className={styles.brandBoxItemDesc}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className={styles.contact} id="contact">
          <div className={styles.contactText}>
            <h1>Contact Us</h1>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam
              quod, voluptatum, quia, voluptas quas voluptates quibusdam
              voluptatibus quae quidem quos nemo. Quisquam, quae. Quisquam
              voluptates quibusdam voluptatibus quae quidem quos nemo.
            </p>
            <button><Link href="/contact">Contact Us</Link></button>
          </div>
          <div className={styles.contactImage}>
            <Image src="/contact.svg" alt="Contact" width={500} height={500} />
          </div>
        </section>
        <footer className={styles.footer}>
          <div className={styles.footerInner}>
            <div className={styles.footerExFo}>
              <div className={styles.footerDetails}>
                <span className="">
                  <Image src="/logo.png" alt="Logo" width={40} height={40} className={styles.footerLogo} />
                </span>
                <span className={styles.footerText}>
                  Social Media
                </span>
                <ul className={styles.footerSocial}>
                  <li className={styles.footerSocialItem}>
                    <a href="https://www.facebook.com/" target="_blank">
                      <FaFacebookSquare className={styles.footerSocialIcon} />
                    </a>
                  </li>
                  <li className={styles.footerSocialItem}>
                    <a href="https://www.instagram.com/" target="_blank">
                      <FaInstagramSquare className={styles.footerSocialIcon} />
                    </a>
                  </li>
                  <li className={styles.footerSocialItem}>
                    <a href="https://twitter.com/" target="_blank">
                      <FaTwitterSquare className={styles.footerSocialIcon} />
                    </a>
                  </li>
                  <li className={styles.footerSocialItem}>
                    <a href="https://www.youtube.com/" target="_blank">
                      <FaYoutubeSquare className={styles.footerSocialIcon} />
                    </a>
                  </li>
                </ul>
              </div>
              <div className={styles.footerLinks}>
                <div className={styles.footerLinksInner}>
                  <span className={styles.footerLinksTitle}>
                    Quick Links
                  </span>
                  <ul className={styles.footerLinksList}>
                    <li className={styles.footerLinksListItem}>
                      <a href="#home">Home</a>
                    </li>
                    <li className={styles.footerLinksListItem}><a
                      href="#about">About</a></li>
                    <li className={styles.footerLinksListItem}><a
                      href="#services">Services</a></li>
                    <li className={styles.footerLinksListItem}><a
                      href="#contact">Contact</a></li>
                  </ul>
                </div>
                <div className={styles.footerLinksInner}>
                  <span className={styles.footerLinksTitle}>
                    Help
                  </span>
                  <ul className={styles.footerLinksList}>
                    <li className={styles.footerLinksListItem}><a
                      href="#">FAQ</a></li>
                    <li className={styles.footerLinksListItem}><a
                      href="#">Privacy Policy</a></li>
                    <li className={styles.footerLinksListItem}><a href="#">Terms
                      & Conditions</a></li>
                  </ul>
                </div>
                <div className={styles.footerLinksInner}>
                  <span className={styles.footerLinksTitle}>
                    Visit
                  </span>
                  <ul className={styles.footerLinksList}>
                    <address className={styles.footerAddress}>
                      <p>
                        102, 2nd Floor,
                        <br />
                        ABC Building,
                        <br />
                        XYZ Road,
                        <br />
                        Mumbai,
                        <br />
                        Maharashtra,
                        <br />
                        India - 400001
                      </p>
                    </address>
                  </ul>
                </div>
              </div>
            </div>
            <div className={styles.footerMade}>
              <span>
                Made with<FaHeart className={styles.footerMadeIcon} />by <a href="https://github.com/sauravhathi"
                  target="_blank" className={styles.footerMadeLink}>XYZ</a>
              </span>
            </div>
          </div>
        </footer>
      </main>
    </>
  )
}
